apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-1618180052
  namespace: default
  labels:
    app: mysql-1618180052
    chart: mysql-1.6.9
data:
  # comentario (apenas exemplo)
  mysql-password: elQ4bHFtaHZYSQ==
  mysql-root-password: TGJtQ0t5RWFPQw==